version: '3.9'
services:
  outfit-app:
    build:
      context: .
      dockerfile: dockerfile  # Match the lowercase name in your structure
    container_name: outfit-recommendation-app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.production
    networks:
      - my_app_network
    restart: always

networks:
  my_app_network:
    external: true  # Use the shared external network
